
size: [512,384]

datasets:
  vitonhd_standard:
    setting: "paired"
    garment_only: True
    image_dir: "zalando/test/image"
    image_postfix: ".jpg"
    segm_dir: "zalando/test/image-parse-v3"
    segm_postfix: ".png"
    densepose_dir: "zalando/test/human_densepose"
    densepose_postfix: "_densepose.png"
    
    garment_image_dir: "zalando/test/cloth"
    garment_image_postfix: ".jpg"
    garment_segm_dir: "zalando/test/cloth-mask"
    garment_segm_postfix: ".jpg"
    garment_densepose_dir: "zalando/test/garment_densepose"
    garment_densepose_postfix: "_densepose.png"

    pair_annotation_path: "zalando/test_pairs.txt"
    image_list: "zalando/test_list.txt"

cond_channels: 32
warped_agnostic:
  seg_preserved_categories: [2,1,3,4] #(hair skin)
  seg_bg_categories: [0] #bg
  seg_outfit_categories: [5] # outfits
  all_outfit_categories: [5,1,3] 
  im2uv_warp_resolution: [64,64]
  uv2im_warp_resolution: [128,128]
  im2uv_warp_interp: "bilinear"
  uv2im_warp_interp: "nearest"

_dfmm_warped_agnostic: # using the segm in the downloaded dfmm dataset
  segm_postfix: ".png"
  seg_preserved_categories: [13,14] #(hair skin)
  seg_bg_categories: [0] #bg
  seg_outfit_categories: [1,2,3,4,5,6,7,8,9,10,11,12,16,17,18,19,20,21,22] # outfits
  warp_resolution: [100,100]
  warp_interp: "bilinear"





